=== shriyavnm7/24071A05U6_WADINTERNAL/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="publisher" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="year" type="xs:gYear"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="category" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== shriyavnm7/24071A05U6_WADINTERNAL/bookstore_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="bookstore.xsd">

    <book id="b1" category="Fiction">
        <title>Harry Porter</title>
        <author>Rowling</author>
        <publisher>HarperTorch</publisher>
        <price>350</price>
        <year>1988</year>
    </book>

    <book id="b2" category="Programming">
        <title>Java Complete Reference</title>
        <author>Herbert Schildt</author>
        <publisher>McGraw Hill</publisher>
        <price>650</price>
        <year>2021</year>
    </book>

    <book id="b3" category="Database">
        <title>Database System Concepts</title>
        <author>Abraham Silberschatz</author>
        <publisher>McGraw Hill</publisher>
        <price>720</price>
        <year>2019</year>
    </book>
</bookstore>
